// flow-typed signature: 2c4fd4dbb0319a6ba367e96b8037e964
// flow-typed version: <<STUB>>/is-base64_v0.0.6/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-base64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-base64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-base64/is-base64' {
  declare module.exports: any;
}

declare module 'is-base64/test/is-base64' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-base64/is-base64.js' {
  declare module.exports: $Exports<'is-base64/is-base64'>;
}
declare module 'is-base64/test/is-base64.js' {
  declare module.exports: $Exports<'is-base64/test/is-base64'>;
}
