// flow-typed signature: 714e10d7039bca22d7121667cc12850b
// flow-typed version: <<STUB>>/rpio_v^0.9.22/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rpio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rpio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rpio/examples/blink' {
  declare module.exports: any;
}

declare module 'rpio/examples/button' {
  declare module.exports: any;
}

declare module 'rpio/examples/dht11' {
  declare module.exports: any;
}

declare module 'rpio/examples/i2c-lcd' {
  declare module.exports: any;
}

declare module 'rpio/examples/padcontrol' {
  declare module.exports: any;
}

declare module 'rpio/examples/pwm-led' {
  declare module.exports: any;
}

declare module 'rpio/examples/spi-at93c46' {
  declare module.exports: any;
}

declare module 'rpio/lib/rpio' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rpio/examples/blink.js' {
  declare module.exports: $Exports<'rpio/examples/blink'>;
}
declare module 'rpio/examples/button.js' {
  declare module.exports: $Exports<'rpio/examples/button'>;
}
declare module 'rpio/examples/dht11.js' {
  declare module.exports: $Exports<'rpio/examples/dht11'>;
}
declare module 'rpio/examples/i2c-lcd.js' {
  declare module.exports: $Exports<'rpio/examples/i2c-lcd'>;
}
declare module 'rpio/examples/padcontrol.js' {
  declare module.exports: $Exports<'rpio/examples/padcontrol'>;
}
declare module 'rpio/examples/pwm-led.js' {
  declare module.exports: $Exports<'rpio/examples/pwm-led'>;
}
declare module 'rpio/examples/spi-at93c46.js' {
  declare module.exports: $Exports<'rpio/examples/spi-at93c46'>;
}
declare module 'rpio/lib/rpio.js' {
  declare module.exports: $Exports<'rpio/lib/rpio'>;
}
